### ISSUE TITLE
pccladmin Add UNBAN command

### ISSUE THREAD

**Issue by schroeder-lvb** [schroeder-lvb/sissm#37]
rcon unbanid steamid

Also update documentation

**Comment by DFSCompad** [comment]
Is there a command to change the path or name for the ban.json file? Like this -log="Insurgency_27102.log" -AdminList=MyAdmins

**Comment by schroeder-lvb** [comment]
@DFSCompad - so far I'm not aware of one.  This is unfortunate because if file path to Bans.json can be specified, we can run multiple instances of gameserver from a single install folder, saving significant amount of storage.  This issue will compound, possibly, when third-party maps begin to appear (year 2020 I hope).

I'm currently experimenting with creating multiple physical folders per install, but replacing only the folder <root>/Insurgency/Content with symbolic link pointing to the master.

**Comment by DFSCompad** [comment]
Hello,

 

i wrote a start/stop/restart/status script for the sissm.

 

You want it? Tell me and i send it to you.

 

Lg DFS Compad

 

Von: JS Schroeder [mailto:notifications@github.com] 
Gesendet: Donnerstag, 17. Oktober 2019 19:00
An: schroeder-lvb/sissm <sissm@noreply.github.com>
Cc: DFSCompad <info@jordan-erfweiler.de>; Mention <mention@noreply.github.com>
Betreff: Re: [schroeder-lvb/sissm] pccladmin Add UNBAN command (#37)

 

@DFSCompad <https://github.com/DFSCompad>  - so far I'm not aware of one. This is unfortunate because if file path to Bans.json can be specified, we can run multiple instances of gameserver from a single install folder, saving significant amount of storage. This issue will compound, possibly, when third-party maps begin to appear (year 2020 I hope).

I'm currently experimenting with creating multiple physical folders per install, but replacing only the folder /Insurgency/Content with symbolic link pointing to the master.

**Comment by schroeder-lvb** [comment]
Staged for release on 0.1.2 (Beta 1.2)
