### ISSUE TITLE
Bot scaled

### ISSUE THREAD

**Issue by DFSCompad** [schroeder-lvb/sissm#52]
Botscaled its not working right. My Gami.ini ist MinimumEnemies=1; MaximumEnemies=48 and Maxplayers=6. Iam alone on the server.
I call 
!bs 10 40 i get 5 bots
!bs 15 40 i get 7 bots
!bs 20 40 i get 10 bots
!bs 30 40 i get 15 bots
!bs 40 40 i get 20 bots
!bs 50 60 i get 25 bots
!bs 60 60 i get 30 bots
!bs 3 60 i get 1 bot

Iam from germany, sorry for the bad english :-)

**Comment by daddymacdave** [comment]
** Set sissm to 1/2 the bots you really want. ** It Doubles it for 2 Waves. so its not an exact number in that respect,.
!bs 5 /10 - is scaled 10 Per Player, Max of 20 total
Weird i know but hope it helps.  

Notice your numbers above that the ACTUAL Bots you see is 1/2 what you requested. Dont use Odd numbers if you want clean math -- but Odd numbers work it will just round like 15 bots to 7 -- Play with the setting, go into game and use TAB to see the actual bots and compare to your setting. - HOPE THIS HELPS! if not msgs or call me on Discord i'm happy to assist. - discord.gg/kG6tc7b

**Comment by schroeder-lvb** [comment]
As DaddyMacDave said, I had to make the decision of calling "number of bots" how many maximum you get between the objectives, OR what you set in minimim/maximumenemies gamemodeproperty.  Because I am coming from the old Insurgency 2014 game, I decided to go with the actual maximum.

Slightly off topic - If you are using maxplayers=6, you are not getting 48 x 2 bots for 6 players, unless you also set MaxPlayersToScaleEnemyCount=6.  Also if your regular players are "fast" gamers, it is very possible you are getting less bots, because they will have captured the objective before 2nd wave has spawned, or still in route.

**Comment by schroeder-lvb** [comment]
Here's an interesting thing you can do, too  - SISSM has a handy command called !gmp (gamemodeproperty).  You can read back what SISSM sent to the Sandstorm server, example:

!bs 5 10
!gmp minimumenemies
!gmp maximumenemies

!bd 4.7
!gmp aidifficulty

You can also override SISSM commands like so:
!gmp minimumenemies 5
!gmp maximumenemies 10
!gmp aidifficulty 0.78

If you enjoy experimenting with server parameters, this method is very convenient.  However, keep in mind that some parameters that works in Game.ini will not work with !gmp (or rcon gamemodeproperty) command.  You can test that by trying to read it back.

**Comment by DFSCompad** [comment]
Thanks for the help. !gmp works well and now i understand how it works.
