### ISSUE TITLE
piantirush

### ISSUE THREAD

**Issue by DFSCompad** [schroeder-lvb/sissm#57]
At Ministry start point this rule comes up 3 times like this: 
*Rule: Ask BEFORE exploding the CACHE
*Rule: Ask BEFORE exploding the CACHE
*Rule: Ask BEFORE exploding the CACHE
At Precinct start point this rule comes up 3 times like this:
*Rule: Ask BEFORE entering Capture Zone
*Rule: Ask BEFORE entering Capture Zone
*Rule: Ask BEFORE entering Capture Zone

**Comment by schroeder-lvb** [comment]
Starting from Beta 2 (0.2.0), if you have any output text in SISSM.CFG file that starts with * character, it will automatically triple print to game screen.

This is because triple printing is VERY noticiable, and nobody will miss it.  

Feel free to remove the "*" prefix on your config file (or disable that feature completely by setting the text to empty string "".

**Comment by DFSCompad** [comment]
Thx, i know this. Good work, i like it.
