### ISSUE TITLE
pidynbots

### ISSUE THREAD

**Issue by DFSCompad** [schroeder-lvb/sissm#58]
This plugin is nice idea and i love it, but this issue i found
Adjusting bots 6:36 difficulty 0.670000 => print on screen :Adjusting bots 6:36 difficulty 6.70000

**Comment by schroeder-lvb** [comment]
Yes I'm sorry about this.  When I designed picladmin (!bs !bf !bd) I made bot counts 2x the NWI system spec, and also used integer number (0-10) for difficulty instead of NWI 0.0-1.0.

The pidynbots speaks the NWI language, but shows on screen the SISSM scale.  I did this to not confuse the players, who is used to seeing !info output on screen.

**Comment by DFSCompad** [comment]
OK thanks i understand, its a problem with NWI programming code.
