### ISSUE TITLE
get server name from rcon in webgen

### ISSUE THREAD

**Issue by k0872** [schroeder-lvb/sissm#61]
instead of having a fixed server name in webgen sissm.cfg, request to get server name via rcon, as our servers are frequently renamed

**Comment by schroeder-lvb** [comment]
gamemodeproperty serverhostname
gamemodeproperty rulesets

**Comment by schroeder-lvb** [comment]
Implemented with backward compatibility.  If "sissm.serverName" in sissm.cfg is set, it will use it.  If it is set to "*" it will use the RCON read value in piwebgen display.  This is because:
1)  Some people have a very long server name which may take up too much space in html display, 
2)  There are many servers with embedded spaces (to get to top of the browser index) or have odd control characters that might not come out well on html,
3)  Some operators may prefer different names displayed on html from the actual server name.

[Staged for release in Beta 2.1 (0.2.1)]
