### ISSUE TITLE
One life server in coop?

### ISSUE THREAD

**Issue by DFSCompad** [schroeder-lvb/sissm#80]
Its nice to have to get a one life server working in coop?

**Comment by schroeder-lvb** [comment]
You mean the Hunt Mode (a la Insurgency 2014)?

This is one of those things to do under the upcoming mod-kit which is advertised to allow 3rd party developers to create a new game mode.

It would be a major overhaul.  You can't just use 'checkpoint' mode and disable respawn.  Since checkpoint has 7-8 objectives and takes 20-30 minutes per round, anyone getting killed in first few minutes will simply disconnect.
